# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none

  - package-ecosystem: pip
    directory: '/ci'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: '/core'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
