#===========================================================================
# allowed DPIs
#===========================================================================
dpis: [254, 190, 127, 56]

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !dnsMatch
    host: maps.google.com
    port: 80
  - !dnsMatch
    host: labs.metacarta.com
    port: 80
     
layouts:
  #===========================================================================
  A4 portrait:
  #===========================================================================
    metaData:
      title: '${title}'

    #-------------------------------------------------------------------------
    mainPage:
      pageSize: A4
      rotation: true
      items:
        - !map
          spacingAfter: 30
          width: 440
          height: 483
      footer: *commonFooter